name = "ims-monitor"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload = { dir = ".output/public" }

[site]
bucket = ".output/public"

[functions]
directory = ".output/server/functions"
